In [1]:
import numpy as np
 
n = np.array((1, 2, 3))
print(n)
print(type(n))
 

[1 2 3]
<class 'numpy.ndarray'>


In [2]:
import numpy as np
 
n = np.array([1, 2, 3])
print(type(n))
 

<class 'numpy.ndarray'>


In [3]:
import numpy as np
 
n = np.array(25)
print(type(n))
print(n.shape)
print("Dimensions = ",n.ndim)

<class 'numpy.ndarray'>
()
Dimensions =  0


In [4]:
import numpy as np
 
n = np.array([10, 20, 30])
print(type(n))
print(n.shape)
print("Dimensions = ",n.ndim)
 

<class 'numpy.ndarray'>
(3,)
Dimensions =  1


In [5]:
import numpy as np
 
n = np.array([[1,3,5],[4,8,12]])
print(type(n))
print(n.shape)
print("Dimensions = ",n.ndim)
 

<class 'numpy.ndarray'>
(2, 3)
Dimensions =  2


In [6]:
import numpy as np
 
n = np.zeros([2, 3])
print(n)
print(type(n))

[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [7]:
import numpy as np
 
n = np.zeros((4, 4))
print(n)
print(type(n))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>


In [8]:
import numpy as np
 
n = np.array([10, 20, 30])
print(n.dtype)

int32


In [9]:
import numpy as np
 
n = np.array(["amit", "rohit", "ashwin", "jadeja", "virat"])
print(n.dtype)
 

<U6


In [10]:
import numpy as np
 
n = np.array(['amit', 'rohit', 'ashwin', 'jadeja', 'virat'], dtype='S5')
print(n.dtype)
 

|S5


In [11]:
import numpy as np
 
n = np.array(['10', '20', '30', '40', '50'])
print(n)
print(n.dtype)
 
n2 = n.astype('i')
print(n2)
print(n2.dtype)

['10' '20' '30' '40' '50']
<U2
[10 20 30 40 50]
int32


In [12]:
import numpy as np
 
n = np.array([10, 20, 30, 40, 50])
print(n[0])
 

10


In [13]:
import numpy as np
 
n = np.array([10, 20, 30, 40, 50])
print(n[3])
 

40


In [14]:
import numpy as np
 
n = np.array([[1,3,5],[4,8,12]])
 
print(n[0,0])
print(n[0,1])
print(n[0,2])

1
3
5


In [15]:
import numpy as np
 
n = np.array([[1,3,5],[4,8,12]])
print(n[1,0])
print(n[1,1])
print(n[1,2])

4
8
12


In [16]:
import  numpy as np
 
n = np.array([[[5,10,15],[20,25,30]],[[35,40,45],[50,55,60]]])
print(n[0,0,0])
print(n[0,0,1])
print(n[0,0,2])
 

5
10
15


In [17]:
import numpy as np
 
n = np.array([[[5,10,15],[20,25,30]],[[35,40,45],[50,55,60]]])
 
print(n[1,0,0])
print(n[1,0,1])
print(n[1,0,2])
 

35
40
45


In [18]:
import numpy as np
 
n = np.array([5, 10, 15])
print('Last element = ', n[-1])
 

Last element =  15


In [19]:
import numpy as np
 
n = np.array([[1, 3, 5], [4, 8, 12]])
print('Last element = ', n[0, -1])
 

Last element =  5


In [20]:
import numpy as np
 
n = np.array([[1,3,5],[4,8,12]])
print('Last element = ', n[1,-1])

Last element =  12


In [21]:
import  numpy as np
 
n = np.array([20, 25, 30, 35, 40, 45, 50, 55, 60, 65])
print(n[1:3])

[25 30]


In [22]:
import numpy as np
 
n = np.array([20, 25, 30, 35, 40, 45, 50, 55, 60, 65])
print(n[2:5])
 

[30 35 40]


In [23]:
import numpy as np
 
n = np.array([20, 25, 30, 35, 40, 45, 50, 55, 60, 65])
print(n[5:])

[45 50 55 60 65]


In [24]:
import numpy as np
 
n = np.array([20, 25, 30, 35, 40, 45, 50, 55, 60, 65])
print(n[:5])

[20 25 30 35 40]


In [25]:
import numpy as np
 
n = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])
print(n[1:10:2])

[10 20 30 40 50]


In [26]:
import numpy as np
   
n = np.array([[10,30,50,70,90,95],[4,8,12,14,16,18]])
print(n[0,2:5])
 

[50 70 90]


In [27]:
import numpy as np
 
n = np.array([[10, 30, 50, 70, 90, 95], [4, 8, 12, 14, 16, 18]])
print(n[0:2, 2:5])

[[50 70 90]
 [12 14 16]]


In [29]:
import numpy as np
 
n = np.array(10)
 
print(n)
print(n.ndim)
print(n.shape)
 

10
0
()


In [30]:
import numpy as np
 
n = np.array([10, 20, 30])
 
print(n)
print(n.ndim)
print(n.shape)
 

[10 20 30]
1
(3,)


In [31]:
import numpy as np
 
# Create a Numpy array
n = np.array([5, 10, 15, 20, 25, 30])
print("One-Dimensional Array = ",n)
 
# Reshape the array
resarr = n.reshape(2, 3)
 
print("Reshaped array (Two-Dimensional) = \n",resarr)

One-Dimensional Array =  [ 5 10 15 20 25 30]
Reshaped array (Two-Dimensional) = 
 [[ 5 10 15]
 [20 25 30]]


In [32]:
import numpy as np
 
# Create a 3D array
n = np.array([[[5, 10, 15],[20, 25, 30]],[[35, 40, 45],[50, 55, 60]]])
print("3D array = \n ",n)
 
# Reshape the array
resarr = n.reshape(-1)
print("\nReshaped to 1D array = ",resarr)

3D array = 
  [[[ 5 10 15]
  [20 25 30]]

 [[35 40 45]
  [50 55 60]]]

Reshaped to 1D array =  [ 5 10 15 20 25 30 35 40 45 50 55 60]


In [33]:
import numpy as np
 
# Create a Numpy 1D array
n = np.array([5, 10, 15, 20, 25, 30])
print("One-Dimensional Array = ",n)
print("Type = ",type(n))
print("DataType = ",n.dtype)
 
print("\nIterating...")
for a in n:
  print(a)

One-Dimensional Array =  [ 5 10 15 20 25 30]
Type =  <class 'numpy.ndarray'>
DataType =  int32

Iterating...
5
10
15
20
25
30


In [34]:
import numpy as np
 
# Create a Numpy 2D array
n = np.array([[5, 10], [15, 20], [25, 30]])
print("Two-Dimensional Array = \n", n)
print("Type = ", type(n))
print("DataType = ", n.dtype)
 
print("\nIterating...")
for a in n:
    print(a)
 

Two-Dimensional Array = 
 [[ 5 10]
 [15 20]
 [25 30]]
Type =  <class 'numpy.ndarray'>
DataType =  int32

Iterating...
[ 5 10]
[15 20]
[25 30]


In [35]:
import numpy as np
 
# Create a Numpy 3D array
n = np.array([[[5, 10], [15, 20]], [[25, 30], [35, 40]]])
print("Three-Dimensional Array = \n",n)
print("Dimensions = ",n.ndim)
print("Type = ",type(n))
print("DataType = ",n.dtype)
 
print("\nIterating...")
for a in n:
  print("Each matrix (2D)=")
  print(a)

Three-Dimensional Array = 
 [[[ 5 10]
  [15 20]]

 [[25 30]
  [35 40]]]
Dimensions =  3
Type =  <class 'numpy.ndarray'>
DataType =  int32

Iterating...
Each matrix (2D)=
[[ 5 10]
 [15 20]]
Each matrix (2D)=
[[25 30]
 [35 40]]


In [36]:
import numpy as np
 
# Create two arrays
n1 = np.array([5, 10, 15, 20])
n2 = np.array([25, 30, 35, 40])
 
print("Iterating array1...")
for a in n1:
    print(a)
 
print("\nIterating array2...")
for a in n2:
    print(a)
 
# Joining arrays
resarr = np.concatenate((n1, n2))
print("\nAfter Joining = ", resarr)
 

Iterating array1...
5
10
15
20

Iterating array2...
25
30
35
40

After Joining =  [ 5 10 15 20 25 30 35 40]


In [37]:
import numpy as np
 
# Create numpy arrays
n1 = np.array([5, 10, 15, 20])
n2 = np.array([25, 30, 35, 40])
 
print("Iterating array1...")
for a in n1:
    print(a)
 
print("\nIterating array2...")
for a in n2:
    print(a)
 
# Join arrays using numpy.stack()
resarr = np.stack((n1, n2))
print("\nAfter Joining = \n", resarr)

Iterating array1...
5
10
15
20

Iterating array2...
25
30
35
40

After Joining = 
 [[ 5 10 15 20]
 [25 30 35 40]]


In [38]:
import numpy as np
 
# Create two arrays
n1 = np.array([5, 10, 15, 20])
n2 = np.array([25, 30, 35, 40])
 
print("Iterating array1...")
for a in n1:
    print(a)
 
print("\nIterating array2...")
for a in n2:
    print(a)
 
# Join arrays using the hstack()
resarr = np.hstack((n1, n2))
print("\nAfter Joining along rows = \n", resarr)

Iterating array1...
5
10
15
20

Iterating array2...
25
30
35
40

After Joining along rows = 
 [ 5 10 15 20 25 30 35 40]


In [39]:
import numpy as np
 
# Create two arrays
n1 = np.array([5, 10, 15, 20])
n2 = np.array([25, 30, 35, 40])
 
print("Iterating array1...")
for a in n1:
    print(a)
 
print("\nIterating array2...")
for a in n2:
    print(a)
 
# Join arrays
resarr = np.vstack((n1, n2))
print("\nAfter Joining along columns = \n", resarr)

Iterating array1...
5
10
15
20

Iterating array2...
25
30
35
40

After Joining along columns = 
 [[ 5 10 15 20]
 [25 30 35 40]]


In [40]:
import numpy as np
 
# Create two arrays
n1 = np.array([5, 10, 15, 20])
n2 = np.array([25, 30, 35, 40])
 
print("Iterating array1...")
for a in n1:
    print(a)
 
print("\nIterating array2...")
for a in n2:
    print(a)
 
# Join arrays
resarr = np.dstack((n1, n2))
print("\nAfter Joining along height = \n", resarr)

Iterating array1...
5
10
15
20

Iterating array2...
25
30
35
40

After Joining along height = 
 [[[ 5 25]
  [10 30]
  [15 35]
  [20 40]]]


In [41]:
# Create two arrays
n1 = np.array([5, 10, 15, 20])
n2 = np.array([25, 30, 35, 40])
 
print("Iterating array1...")
for a in n1:
    print(a)
 
print("\nIterating array2...")
for a in n2:
    print(a)
 
# Join arrays
resarr = np.column_stack((n1, n2))
print("\nAfter Joining = \n", resarr)

Iterating array1...
5
10
15
20

Iterating array2...
25
30
35
40

After Joining = 
 [[ 5 25]
 [10 30]
 [15 35]
 [20 40]]


In [42]:
import numpy as np
 
# Create a Numpy array
n = np.array([10, 20, 30, 40, 50, 60])
 
print("Iterating array...")
for a in n:
    print(a)
 
# splitting array into 2
resarr = np.array_split(n, 2)
 
print("\nArray after splitting i.e. returns 2 arrays");
for a in resarr:
    print(a)

Iterating array...
10
20
30
40
50
60

Array after splitting i.e. returns 2 arrays
[10 20 30]
[40 50 60]


In [43]:
import numpy as np
 
n = np.array([10, 20, 30, 40, 50, 60])
 
print("Iterating array...")
for a in n:
  print(a)
 
# splitting into 2
resarr = np.array_split(n, 2)
 
print("\nArray after splitting i.e. returns 2 arrays");
print(resarr)
 
print("\nAccess splitted array individually...");
print("Array1 = ",resarr[0])
print("Array2 = ",resarr[1])

Iterating array...
10
20
30
40
50
60

Array after splitting i.e. returns 2 arrays
[array([10, 20, 30]), array([40, 50, 60])]

Access splitted array individually...
Array1 =  [10 20 30]
Array2 =  [40 50 60]


In [44]:
import  numpy as np
 
n = np.array([[1,3,5],[4,8,12]])
 
print("Iterating array...")
for a in n:
 print(a)
 
# splitting into 2
resarr = np.array_split(n, 2)
 
print("\nArray after splitting (returns 2 arrays)");
print(resarr)
 
print("\nAccess splitted array individually...");
print("Array1 = ",resarr[0])
print("Array2 = ",resarr[1])
 

Iterating array...
[1 3 5]
[ 4  8 12]

Array after splitting (returns 2 arrays)
[array([[1, 3, 5]]), array([[ 4,  8, 12]])]

Access splitted array individually...
Array1 =  [[1 3 5]]
Array2 =  [[ 4  8 12]]


In [45]:
import numpy as np
 
# Create a Numpy Array
n = np.array([10, 20, 30, 40, 50, 30])
 
print("Iterating array...")
for a in n:
    print(a)
 
# Searching a specific value 30
res = np.where(n == 30)
 
print("\nElement 30 found at following indexes:")
print(res)

Iterating array...
10
20
30
40
50
30

Element 30 found at following indexes:
(array([2, 5], dtype=int64),)


In [46]:
import numpy as np
 
# Create a 1D integer array
n = np.array([50, 25, 35, 15, 55, 75, 65, 60, 30, 45])
 
print("Iterating array...")
for a in n:
    print(a)
 
# Sort the array using the sort() method
print("\nSorted array = ", np.sort(n))
 

Iterating array...
50
25
35
15
55
75
65
60
30
45

Sorted array =  [15 25 30 35 45 50 55 60 65 75]


In [47]:
import numpy as np
 
# Create a Numpy strungs array
n = np.array(['java', 'keras', 'android', 'express', 'jquery'])
 
print("Iterating array...")
for a in n:
    print(a)
 
# Sort the array
print("\nSorted array = ", np.sort(n))

Iterating array...
java
keras
android
express
jquery

Sorted array =  ['android' 'express' 'java' 'jquery' 'keras']


In [48]:
import numpy as np
 
# Create Numpy 2d array
n = np.array([[5, 3, 7, 9, 6], [15, 25, 13, 20, 12]])
 
print("Iterating 2D array...")
for a in n:
    print(a)
 
# Sort the array
print("\nSorted 2D array =\n ", np.sort(n))
 

Iterating 2D array...
[5 3 7 9 6]
[15 25 13 20 12]

Sorted 2D array =
  [[ 3  5  6  7  9]
 [12 13 15 20 25]]


In [49]:
import numpy as np
 
# Create a numpy 3x5 array
n = np.array([[2, 5, 7, 9, 6], [15, 25, 35, 45, 55], [100, 200, 300, 400, 500]])
 
print("Iterating 2D array...")
for a in n:
    print(a)
 
print("\nMinimum value = ", n.min())
print("\nMinimum value with axis 0 (vertical axes) = ", n.min(axis=0))
print("\nMinimum value with axis 1 (horizontal axes) = ", n.min(axis=1))
 

Iterating 2D array...
[2 5 7 9 6]
[15 25 35 45 55]
[100 200 300 400 500]

Minimum value =  2

Minimum value with axis 0 (vertical axes) =  [2 5 7 9 6]

Minimum value with axis 1 (horizontal axes) =  [  2  15 100]


In [50]:
import numpy as np
 
# Create two arrays
n1 = np.array([5, 10, 15, 20])
n2 = np.array([5, 15, 30, 40])
 
print("Iterating array1...")
for a in n1:
    print(a)
 
print("\nIterating array2...")
for a in n2:
    print(a)
 
# Find intersection using the intersect1d() method
resarr = np.intersect1d(n1, n2)
print("\nIntersection = \n", resarr)

Iterating array1...
5
10
15
20

Iterating array2...
5
15
30
40

Intersection = 
 [ 5 15]


In [51]:
import numpy as np
 
# Create two arrays
n1 = np.array([10, 50, 30, 20, 60, 40])
n2 = np.array([80, 50, 90, 100, 40, 70])
 
print("Iterating array1...")
for a in n1:
    print(a)
 
print("\nIterating array2...")
for a in n2:
    print(a)
 
# Find the intersection
resarr = np.intersect1d(n1, n2)
print("\nIntersection (sorted result) = \n", resarr)

Iterating array1...
10
50
30
20
60
40

Iterating array2...
80
50
90
100
40
70

Intersection (sorted result) = 
 [40 50]


In [52]:
import  numpy as np
 
# Create two arrays
n1 = np.array([10, 20, 30, 40, 50])
n2 = np.array([60, 70, 80, 90, 100])
 
print("Iterating array1...")
for a in n1:
    print(a)
 
print("\nIterating array2...")
for a in n2:
    print(a)
 
# Find the intersection
resarr = np.intersect1d(n1, n2)
print("\nIntersection (different elements) = \n", resarr)

Iterating array1...
10
20
30
40
50

Iterating array2...
60
70
80
90
100

Intersection (different elements) = 
 []


In [53]:
import numpy as np
 
# Create two arrays
n1 = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])
n2 = np.array([30, 35, 50, 55, 60, 65, 75, 85, 95, 100])
 
print("Iterating array1...")
for a in n1:
    print(a)
 
print("\nIterating array2...")
for a in n2:
    print(a)
 
# n1 - n2
diffarr = np.setdiff1d(n1, n2)
print("\nDifference = \n", diffarr)
 

Iterating array1...
5
10
15
20
25
30
35
40
45
50

Iterating array2...
30
35
50
55
60
65
75
85
95
100

Difference = 
 [ 5 10 15 20 25 40 45]


In [54]:
import numpy as np
 
# Create two arrays
n1 = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])
n2 = np.array([30, 35, 50, 55, 60, 65, 75, 85, 95, 100])
 
print("Iterating array1...")
for a in n1:
    print(a)
 
print("\nIterating array2...")
for a in n2:
    print(a)
 
# Get the difference 
resarr = np.setdiff1d(n2, n1)
print("\nDifference = \n", resarr)

Iterating array1...
5
10
15
20
25
30
35
40
45
50

Iterating array2...
30
35
50
55
60
65
75
85
95
100

Difference = 
 [ 55  60  65  75  85  95 100]


In [55]:
import numpy as np
 
# Create arrays
n1 = np.array([15, 20, 25, 30])
n2 = np.array([65, 75, 85, 95])
 
print("Array1 =", n1)
print("Array2 =", n2)
 
# Add the arrays elements
resarr = np.sum([n1, n2])
print("Sum = ", resarr)
 

Array1 = [15 20 25 30]
Array2 = [65 75 85 95]
Sum =  410


In [56]:
import numpy as np
 
# Create two arrays
n1 = np.array([15, 20, 25, 30])
n2 = np.array([65, 75, 85, 95])
 
print("Array1 =", n1)
print("Array2 =", n2)
 
# Add column values using axis parameter
resarr = np.sum([n1, n2], axis=0)
print("Sum = ", resarr)

Array1 = [15 20 25 30]
Array2 = [65 75 85 95]
Sum =  [ 80  95 110 125]


In [57]:
import numpy as np
 
# Create two arrays
n1 = np.array([15, 20, 25, 30])
n2 = np.array([65, 75, 85, 95])
 
print("Array1 =", n1)
print("Array2 =", n2)
 
# Add individual array values using axis parameter
resarr = np.sum([n1, n2], axis=1)
print("Sum result= ", resarr)

Array1 = [15 20 25 30]
Array2 = [65 75 85 95]
Sum result=  [ 90 320]


In [58]:
import numpy as np
 
# Create two arrays
n1 = np.array([15, 20, 25, 30])
n2 = np.array([65, 75, 85, 95])
 
print("Array1 =", n1)
print("Array2 =", n2)
 
# Subtract Numpy arrays
resarr = np.subtract(n1, n2)
print("Subtraction result = ", resarr)
 

Array1 = [15 20 25 30]
Array2 = [65 75 85 95]
Subtraction result =  [-50 -55 -60 -65]


In [59]:
import numpy as np
 
# Create Numpy arrays
n1 = np.array([15, 20, 25, 30])
n2 = np.array([65, 75, 85, 95])
 
print("Array1 =", n1)
print("Array2 =", n2)
 
# Multiply Numpy arrays
resarr = np.multiply(n1, n2)
print("Multiplication result = ", resarr)

Array1 = [15 20 25 30]
Array2 = [65 75 85 95]
Multiplication result =  [ 975 1500 2125 2850]


In [60]:
import numpy as np
 
# Create two Numpy arrays
n1 = np.array([15, 20, 25, 30])
n2 = np.array([65, 75, 85, 95])
 
print("Array1 =", n1)
print("Array2 =", n2)
 
# Divide arrays
resarr = np.divide(n2, n1)
print("Division Result = ", resarr)

Array1 = [15 20 25 30]
Array2 = [65 75 85 95]
Division Result =  [4.33333333 3.75       3.4        3.16666667]


In [61]:
import numpy as np
 
# Create two arrays
n1 = np.array([15, 20, 25, 30])
n2 = np.array([65, 75, 85, 95])
 
print("Array1 =", n1)
print("Array2 =", n2)
 
# performing addition on each element
n1 = n1 + 10;
n2 = n2 + 20;
 
print("Array1 (updated) ", n1)
print("Array2 (updated) ", n2)

Array1 = [15 20 25 30]
Array2 = [65 75 85 95]
Array1 (updated)  [25 30 35 40]
Array2 (updated)  [ 85  95 105 115]


In [62]:
import numpy as np
 
# Create two Numpy arrays
n1 = np.array([15, 20, 25, 30])
n2 = np.array([65, 75, 85, 95])
 
print("Array1 =", n1)
print("Array2 =", n2)
 
# performing subtraction on each element          
n1 = n1 - 5;
n2 = n2 - 10;
 
print("Array1 (updated) ", n1)
print("Array2 (updated) ", n2)
 

Array1 = [15 20 25 30]
Array2 = [65 75 85 95]
Array1 (updated)  [10 15 20 25]
Array2 (updated)  [55 65 75 85]


In [63]:
import numpy as np
 
# Create two arrays
n1 = np.array([15, 20, 25, 30])
n2 = np.array([65, 75, 85, 95])
 
print("Array1 =", n1)
print("Array2 =", n2)
 
# performing multiplication on each element          
n1 = n1 * 5;
n2 = n2 * 10;
 
print("Array1 (updated) ", n1)
print("Array2 (updated) ", n2)
 

Array1 = [15 20 25 30]
Array2 = [65 75 85 95]
Array1 (updated)  [ 75 100 125 150]
Array2 (updated)  [650 750 850 950]


In [64]:
import  numpy as np
 
# Create two arrays
n1 = np.array([15, 20, 25, 30])
n2 = np.array([65, 75, 85, 95])
 
print("Array1 =", n1)
print("Array2 =", n2)
 
# performing division on each element
n1 = n1 / 5;
n2 = n2 / 5;
 
print("Array1 (updated) ", n1)
print("Array2 (updated) ", n2)
 

Array1 = [15 20 25 30]
Array2 = [65 75 85 95]
Array1 (updated)  [3. 4. 5. 6.]
Array2 (updated)  [13. 15. 17. 19.]


In [65]:
import numpy as np
 
# Create two arrays
n1 = np.array([15, 20, 25, 30])
n2 = np.array([65, 75, 85, 95])
 
print("Array1 =", n1)
print("Array2 =", n2)
 
# mean
resmean1 = np.mean(n1);
resmean2 = np.mean(n2);
 
print("\nArray1 mean = ", resmean1)
print("Array2 mean = ", resmean2)

Array1 = [15 20 25 30]
Array2 = [65 75 85 95]

Array1 mean =  22.5
Array2 mean =  80.0


In [66]:
import numpy as np
 
# Create two arrays
n1 = np.array([15, 20, 25, 30])
n2 = np.array([65, 75, 85, 95])
 
print("Array1 =", n1)
print("Array2 =", n2)
 
# median
resmedian1 = np.median(n1);
resmedian2 = np.median(n2);
 
print("\nArray1 median = ", resmedian1)
print("Array2 median = ", resmedian2)

Array1 = [15 20 25 30]
Array2 = [65 75 85 95]

Array1 median =  22.5
Array2 median =  80.0


In [67]:
import numpy as np
 
# Create two arrays
n1 = np.array([15, 20, 25, 30])
n2 = np.array([65, 75, 85, 95])
 
print("Array1 =", n1)
print("Array2 =", n2)
 
# standard deviation
resstd1 = np.std(n1);
resstd2 = np.std(n2);
 
print("\nArray1 Standard Deviation = ", resstd1)
print("Array2 Standard Deviation = ", resstd2)
 

Array1 = [15 20 25 30]
Array2 = [65 75 85 95]

Array1 Standard Deviation =  5.5901699437494745
Array2 Standard Deviation =  11.180339887498949


In [68]:
from numpy import random
 
# Get random number from 0 to 5
n = random.randint(5)
 
print("Random number= ",n)

Random number=  0


In [69]:
from numpy import random
 
# get 3 random numbers as array elements from 0 to 10
n = random.randint(10, size=(3))
 
print("Random number= ",n)

Random number=  [0 2 3]


In [70]:
from numpy import random
 
# get a random number from the following array values
n = random.choice([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
 
print("Random number= ",n)

Random number=  30


In [71]:
import numpy as np
 
# Create a Numpy array
n = np.array([1, 2, 3, 4, 5])
print("Array\n",n)
 
# log2
print("\nResult\n",np.log2(n))

Array
 [1 2 3 4 5]

Result
 [0.         1.         1.5849625  2.         2.32192809]


In [72]:
import numpy as np
 
# Create an array
n = np.array([1, 2, 3, 4, 5])
print("Array\n",n)
 
# log10
print("\nResult\n",np.log10(n))

Array
 [1 2 3 4 5]

Result
 [0.         0.30103    0.47712125 0.60205999 0.69897   ]


In [73]:
import numpy as np
 
# Two numbers
a = 3
b = 12
 
# Finding LCM
res = np.lcm(a, b)
 
print("LCM of two numbers = ", res)

LCM of two numbers =  12


In [74]:
import numpy as np
 
# Two numbers
a = 2
b = 8
 
# finding GCD (HCF)
res = np.gcd(a, b)
 
print("GCD of two numbers = ", res)

GCD of two numbers =  2
